[package]
name = "loop-stream"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "A custom streaming tool for episodes base on ffmpeg tool."
authors = ["chekun"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"